### ISSUE TITLE
add support for fetchFromGitea 

### ISSUE THREAD

**Issue by SuperSandro2000** [Mic92/nix-update#133]
We should also support gitea that for example https://github.com/NixOS/nixpkgs/pull/208964/files can be updated.

**Comment by figsoda** [comment]
these are the API end points if you someone wants to work on it, It might also be possible with atom feeds but I'm not familiar with that

https://try.gitea.io/api/swagger#/repository/repoListReleases
https://try.gitea.io/api/swagger#/repository/repoGetAllCommits

**Comment by figsoda** [comment]
https://github.com/Mic92/nix-update/pull/134
