### ISSUE TITLE
trace some variables to make debugging easier

### ISSUE THREAD

**Issue by colemickens** [Mic92/nix-update#146]
Hi.

I'm trying to use nix-update to update `nushell` to the tip-of-tree of my fork. I got it to work once, but now it seems to fail:

```
error: assertion '((substring 0 outPathLen file) == outPath)' failed
```

It would be helpful if outPath/file were traced so I could have a better idea of what's going on

**Comment by figsoda** [comment]
#155

**Comment by Mic92** [comment]
fixed in https://github.com/Mic92/nix-update/pull/155
