### ISSUE TITLE
rust package updates, then breaks on next (should be idempotent) invocation

### ISSUE THREAD

**Issue by colemickens** [Mic92/nix-update#149]
I just noticed this as I was packing up but wanted to file it real quick.

`--commit` behaves... other than I would expect.

Right now, I'm running it in a loop with two packages. I'm running:

`nix-update --flake --build --format --version branch --commit '.#pkgs.x86_64-linux.{pkgname}` and it's doing this:

* makes a commit: 
  ```
  commit 1f7fb506e2bed516f80497e7fc5af17bbedda86e (HEAD -> main)
  Author: Cole Mickens <cole.mickens@gmail.com>
  Date:   Thu Apr 6 16:00:45 2023 -0500

      pkgs.x86_64-linux.nushell: 943d0d1b2dc83e89c5f87338505607e3beaf4222 -> unstable-2023-04-06

      Diff: https://github.com/nushell/nushell/compare/943d0d1b2dc83e89c5f87338505607e3beaf4222...a29b61bd4f63469fdeab5aee25ab5f004d0413d7
  ```
* spits this out and stops with `-1` exit code
  ```
  0 / 1 have been reformatted
  On branch main
  Your branch and 'origin/main' refer to different commits.
    (use "git status --ahead-behind" for details)

  nothing to commit, working tree clean
  ```

**Comment by colemickens** [comment]
Further, if I run the same command afterward...

It seems to do some other modification (which it shouldn't be a29... is the latest revision)

And then opens **an interactive commit message text editor**:

```
0 / 1 have been reformatted
On branch main
Your branch and 'origin/main' refer to different commits.
  (use "git status --ahead-behind" for details)

nothing to commit, working tree clean
```

But when I close it... I can see that the update FAILED, and then it returns 0 and proceeds anyway...

**Comment by colemickens** [comment]
The failure seems to include this bit:

```
│trying https://github.com/nushell/nushell/archive/unstable-2023-04-06.tar.gz 
```

Not sure why it would be doing that, it recorded the correct revision on the first pass.

**Comment by colemickens** [comment]
here's the good commit where it updated: https://github.com/colemickens/nixcfg/commit/1f7fb506e2bed516f80497e7fc5af17bbedda86e

and here's what it did when I re-ran (expecting idempotency): https://github.com/colemickens/nixcfg/commit/8c66add524afc50f5ff0d5e4105d1e8b8aed6392

cc: @figsoda in case it's related to the recent rust change

**Comment by Mic92** [comment]
The only thing it runs is git-add and git-commit so if it breaks for your repository, check if you can run git-commit normally: https://github.com/Mic92/nix-update/blob/329edce9f781e70bda9b98a13c16182c68836f10/nix_update/__init__.py#L35

**Comment by colemickens** [comment]
I think this is more of a symptom of a different issue. I've re-titled the thread to better reflect the behavior I've shown.

**Comment by colemickens** [comment]
Actually, I was overloading rev/version and might've even had the derivation pointed at the wrong organization.

Now that I've fixed the derivation, I am still seeing odd behavior. It's still trying to commit ... twice...? And the latter is an empty commit so it stops and returns -1.

It is behaving "idempotently" as I expected. It updates nushell, builds it, commits it, and then tries to commit nothing. If I re-run, it's a no-op for the update, and then still tries to commit nothing.

I'll dig into it a bit and post if I figure anything out.

**Comment by colemickens** [comment]
Yeah, I don't know what's going on. Again, it definitely made a commit successfully and then tries to commit nothing and fails.

```
>wezterm-unstable> stripping (with command strip and flags -S) in  /nix/store/9iy1qqdjjhfxqqjydlhi7g229alr5cv1-wezterm-unstable-2023-04-07/bin
0 / 1 have been reformatted
On branch main
Your branch and 'origin/main' refer to different commits.
  (use "git status --ahead-behind" for details)

nothing to commit, working tree clean
```

but `git log -p` shows that it did commit just fine:

```
╭ zeph  ~/code/nixcfg 518.49s ✘1
╰─▶ git log -p .
Date:   Fri Apr 7 18:13:19 2023 -0500

    pkgs.x86_64-linux.wezterm: unstable-2023-04-06 -> unstable-2023-04-07

    Diff: https://github.com/colemickens/wezterm/compare/5eb6bc15372bb07c72180aa2b744edb0872f84fe...f4bcbe42618e868fa61ab7821f07a99db06db633

diff --git a/pkgs/wezterm/default.nix b/pkgs/wezterm/default.nix
index c6dd1509..486d3afd 100644
--- a/pkgs/wezterm/default.nix
+++ b/pkgs/wezterm/default.nix
@@ -38,8 +38,8 @@ let
 in
 rustPlatform.buildRustPackage rec {
   pname = "wezterm";
-  version = "unstable-2023-04-06";
-  rev = "5eb6bc15372bb07c72180aa2b744edb0872f84fe";
+  version = "unstable-2023-04-07";
+  rev = "f4bcbe42618e868fa61ab7821f07a99db06db633";

   src = fetchFromGitHub {
     owner = owner;
```


Furthermore, the logic for detecting an upgrade doesn't seem to work if there are two updates in the same day... I feel like it should be using the rev for that instead of the version string.

**Comment by figsoda** [comment]
The issues seems to be the interaction between `--version branch` and `rev = version`. I can reproduce https://github.com/Mic92/nix-update/issues/149#issuecomment-1499632424 when I run nix-update second time, probably has something to do with the latest revision being the same as the current revision. setting version to something like "unstable-*" might be able to work around the bug

**Comment by colemickens** [comment]
It doesn't. Even after setting version to a matching string and backing out
the empty commit, it still repros.

By doing this manually and running it for each package, I have a list of
commits with appropriate messages and version strings, but still the weird
extra empty commit issue and then failure.

Also, it really seems like it can't update multiple times in one day
because it's using the version string instead of rev to determine if it
needs to update.

I might try to look at this later. It also seems odd how "git add" is used,
instead of just directly commiting the updated file loc...

**Comment by colemickens** [comment]
I'm so sorry, the script I have does it's own commit, which is why I was seeing the extra empty commit happening.

I'm going to go ahead and close this, and open a new issue(s) regarding multiple updates on the same day, if I confirm that is in case what I think I've been observing along the way here.
