### ISSUE TITLE
nix-update will not update a package twice in one day (w/ version=branch)

### ISSUE THREAD

**Issue by colemickens** [Mic92/nix-update#151]
As I had observed previously, it seems that `nix-update` will not update a package multiple times in one day.

Example:
```
Not updating version, already unstable-2023-04-10
```

However, if we look at that package:

```
╭ zeph  ~/code/nixcfg 0.02s
╰─▶ cat ./pkgs/nushell/default.nix | ^grep -E "(rev|version|owner|repo) = \""
    version = "unstable-2023-04-10";
    rev = "0e2340051019b581bdb3eeed37310d637b7255c1";
    owner = "colemickens";
    # owner = "nushell";

╭ zeph  ~/code/nixcfg 0.46s
╰─▶ git ls-remote https://github.com/colemickens/nushell | head -1
de76c7a57debfb813f21ff0aedfcfe87b828f20d        HEAD
```

As shown, there is in fact a newer rev to update to.

Maybe this is intentional, or by design, but it would be nice if the `rev` were used instead to determine if an update is necessary.

**Comment by figsoda** [comment]
could you test if #152 fixes the issue for you?
