### ISSUE TITLE
Unable to generate a `Cargo.lock` file for repositories that do not have one

### ISSUE THREAD

**Issue by nickgerace** [Mic92/nix-update#164]
It would be great if `nix-update` had the ability to generate `Cargo.lock` file. Of course, this would have to be explicit and not default behavior.

We encountered this issue when working on adding [reindeer](https://github.com/facebookincubator/reindeer) to nixpkgs. More context here: https://github.com/NixOS/nixpkgs/pull/232699#discussion_r1198358248.

**Comment by doronbehar** [comment]
Similarly, it'd be great if there was also support for updating vendored `package-lock.json` files.

**Comment by nickgerace** [comment]
Thank you @natsukium @Mic92!
