### ISSUE TITLE
Switch from `cargoSha256` to `cargoHash`

### ISSUE THREAD

**Issue by asymmetric** [Mic92/nix-update#177]
If a package has a SRI hash, then the manual [recommends](https://nixos.org/manual/nixpkgs/stable/#compiling-rust-applications-with-cargo) using `cargoHash`.

It could be handy if `nix-update` could handle this, to avoid small annoyances like https://github.com/NixOS/nixpkgs/pull/246037#pullrequestreview-1553423677.

**Comment by Mic92** [comment]
We are currently don't have robust enough mechanism in nix-update to perform refactorings like that: https://github.com/Mic92/nix-update/pull/209
