### ISSUE TITLE
attribute names should not be quoted unconditionally

### ISSUE THREAD

**Issue by natsukium** [Mic92/nix-update#181]
The PRs associated with #178 added the escaping of attribute names.
Because of this, it is impossible to evaluate packages with namespaces such as `python3Packages` in nixpkgs.

```
$ nix run github:Mic92/nix-update/0.19.2#nix-update -- python310Packages.streamlit

...
error: attribute '"python310Packages.streamlit"' missing

       at «string»:8:9:

            7|            (if args ? overlays then { overlays = [ ]; } else {});
            8|   pkg = (pkgs inputs)."python310Packages.streamlit";
             |         ^
            9|   sanitizePosition = x: x;
Traceback (most recent call last):
...
```

> Really, we could just do this unconditionally, since there isn't any real difference between x.y and x."y" other than variable interpolation?

This is precisely the problem. Quoting them prevents expanding the namespace.

**Comment by figsoda** [comment]
oops, I didn't think about that

#182 should be able to fix this, sorry about that
