### ISSUE TITLE
update `vendorHash` of local Go module

### ISSUE THREAD

**Issue by katexochen** [Mic92/nix-update#212]
Not sure this is in scope of nix-update, but updating the `vendorHash` of a local module is a common task that doesn't seem to be supported by nix-update:

```nix
foo = buildGoModule {
  pname = "my-package";
  version = "1.1.1"
  src = ./.;
  vendorHash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="; # update
};
```

**Comment by Mic92** [comment]
Shouldn't work if you use `--version=skip`?

**Comment by katexochen** [comment]
:man_facepalming: works indeed.
