### ISSUE TITLE
Add feature to allow blacklisting package versions

### ISSUE THREAD

**Issue by monyarm** [Mic92/nix-update#220]
I'm having an issue where nix-update thinks the latest version of a repo is called stacktrace, due to it having a tag with the same name. It completely ignores the actual version (v1.1.3-rc.5).
A way to blacklist certain versions would be useful.

**Comment by SuperSandro2000** [comment]
You could achieve that with the regex filter

**Comment by Mic92** [comment]
Yeah. There are too many different version formats and regexes is easiest way to filter through that.
