### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by GaetanLepage** [Mic92/nix-update#224]
Hi,

Would it be possible to create a new (minor) release of `nix-update` ?
Like so, it could ship with https://github.com/Mic92/nix-update/commit/a566b9bdb17bc394cbbefdd274b54432edec6d3f.

Thanks for this very very convenient tool !

**Comment by Mic92** [comment]
https://github.com/Mic92/nix-update/releases/tag/1.2.0

**Comment by GaetanLepage** [comment]
Thanks !
