### ISSUE TITLE
Switch to `nixfmt` as formatter

### ISSUE THREAD

**Issue by Guanran928** [Mic92/nix-update#253]
`nixfmt` is now the official formatter for Nix code (https://github.com/NixOS/rfcs/pull/166),

should be trivial, `nixpkgs-fmt` only appears 4 times in `nix-update`'s src.

https://github.com/Mic92/nix-update/blob/c8ba353d2222993423b6f69d08c02370cc599522/nix_update/__init__.py#L329

**Comment by Mic92** [comment]
Fixed by https://github.com/Mic92/nix-update/pull/251
