### ISSUE TITLE
sub-hashes can be wrong if they depend on each other

### ISSUE THREAD

**Issue by martinetd** [Mic92/nix-update#302]
`nix_update/update.py`'s `update` updates hashes in a fixed order (`update_go_modules_hash`, `update_cargo_vendor_deps_hash`...)
but if multiple such hashes are required, it's possible that the earlier hash actually depends on a later one.

To give a concrete example, rmfakecloud as of https://github.com/NixOS/nixpkgs/pull/358324/commits/632b589b55eec8fcbad9045e6e51338962ea1bf4 contains a go module with pnpmDeps.

building rmfakecloud.goModules pulls in pnpmDeps so building it with a fake hash fails due to a bad hash in pnpmDeps; and the update script will take that pnpmDep's hash and enter it in the go's `vendorHash`

Just changing the way the hashes are evaluated fixes this issue:

```diff
diff --git a/nix_update/update.py b/nix_update/update.py
index 605ac2f6f3bb..9dd8eaf73939 100644
--- a/nix_update/update.py
+++ b/nix_update/update.py
@@ -469,6 +469,9 @@ def update(opts: Options) -> Package:
 
     # if no package.hash was provided we just update the other hashes unconditionally
     if update_hash or not package.hash:
+        if package.pnpm_deps:
+            update_pnpm_deps_hash(opts, package.filename, package.pnpm_deps)
+
         if package.go_modules:
             update_go_modules_hash(opts, package.filename, package.go_modules)
 
@@ -494,9 +497,6 @@ def update(opts: Options) -> Package:
         if package.npm_deps:
             update_npm_deps_hash(opts, package.filename, package.npm_deps)
 
-        if package.pnpm_deps:
-            update_pnpm_deps_hash(opts, package.filename, package.pnpm_deps)
-
         if package.yarn_deps:
             update_yarn_deps_hash(opts, package.filename, package.yarn_deps)
 
```

But that'll obviously break updating pnpmDeps hash if that hash depends on a go module (I don't think that's likely, but it's technically possible...)

So, would it make sense/be possible to interface something to specify the order in which we want these to run?
Better, could we detect they depend on each other and compute an appropriate order automatically?

(An alternative less efficient than controlling the order would be to try to run these multiple times (e.g. updating go, pnpm, go would ultimately fill in the correct go hash), but that's a bit too much of a kludge in my opinion so not suggesting that one)

btw, I don't think such package is common enough to warrant complexifying the code too much, mostly wondering.

Thanks!

**Comment by pbsds** [comment]
A flag to loop through the all hashes until a fixed point is reached might make sense.

**Comment by Mic92** [comment]
Maybe have a look at what files are actually changing when the checksum are updated.

**Comment by martinetd** [comment]
Yes, I looked at that as well as I agree not being dependant on each other would be ideal.

The problem is that the go update evaluated `rmfakecloud.goModules`, but that goModules item is an override of the derivation that includes everything including "unrelated" env variables
(this had also caused me trouble to build in the first place, TomaSajt in https://github.com/NixOS/nixpkgs/issues/358844 suggested using env instead as that is inherited...)
The work to make goModules use hooks instead of overriding the derivation as it currently does ( https://github.com/NixOS/nixpkgs/pull/353526 ) should help with that, but as things stand I don't see a way around it.
If we had a subtarget like goModules.vendored or something we could use that, but that doesn't exist so goModules will always include everything else and come last as far as I understand.


In that sense, we could probably just move go last in the order and forget about this...

**Comment by martinetd** [comment]
Ah, actually I was misunderstanding how buildGoModule works, I now agree it should be possible to split it; I'll try a bit harder to push forward that way.

Closing this for now.
