### ISSUE TITLE
Migrate from `offlineCache` to `yarnOfflineCache`

### ISSUE THREAD

**Issue by Moraxyc** [Mic92/nix-update#306]
It seems that `nix-update` still uses `offlineCache` to determine whether `yarnDeps` needs to be updated. But the documentation currently recommends using `yarn{Config,Build}Hook`, and the field used  is `yarnOfflineCache`

Related PR: https://github.com/NixOS/nixpkgs/issues/324246
Doc: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#yarn-javascript-yarn

https://github.com/Mic92/nix-update/blob/2f7610ab01a7f4258875421e13a08883bec82fa0/nix_update/eval.py#L197

https://github.com/Mic92/nix-update/blob/2f7610ab01a7f4258875421e13a08883bec82fa0/nix_update/update.py#L374-L376

**Comment by Mic92** [comment]
Pull requests welcome.
