### ISSUE TITLE
Using updateScript with flake

### ISSUE THREAD

**Issue by 0x006E** [Mic92/nix-update#308]
How to use updateScript when using flakes?
This line seems to set has_update_script to false if it's a flake

https://github.com/Mic92/nix-update/commit/e5f57c258c91c71f896af0d2b3da1674f24e35ad#diff-42490f7d92fc20d3562eeac3666505b3866ec7dace97b62ba2d2068c7184e8c7R74

I couldn't find any reason why that is. I am trying to setup auto updates in my config for packages that are not nixpkgs. 
my config https://github.com/0x006E/dotfiles/

**Comment by Mic92** [comment]
This functionality is only part of nixpkgs https://github.com/Mic92/nix-update/blob/e3f3d83df8f5b3a90217e97310543ccdd497a53b/nix_update/update.py#L463

**Comment by 0x006E** [comment]
Ooh. okay. Thank you for your help.
