### ISSUE TITLE
Support finding latest version for instances of GitLab

### ISSUE THREAD

**Issue by worldofpeace** [Mic92/nix-update#4]
Currently it only supports `gitlab.com`, but people can create instances of GitLab and it's prevalent in nixpkgs. Examples like `gitlab.gnome.org` `gitlab.freedesktop.org` `salsa.debian.org`

**Comment by Mic92** [comment]
If `fetchFromGitLab` is used I can use the API format as heuristic:

i.e.:

"https://gitlab.gnome.org/api/v4/projects/GNOME%2Fgnome-tour/repository/archive.tar.gz?sha=0.0.1"

**Comment by worldofpeace** [comment]
@Mic92 Yep, I added instance support to `fetchFromGitLab` a while ago so everything in nixpkgs should be using that.

**Comment by Mic92** [comment]
I have something almost ready. Just want to combine this with a different feature.
