### ISSUE TITLE
Provide overlay

### ISSUE THREAD

**Issue by blaggacao** [Mic92/nix-update#54]
In order to be able to pull in latest versions into my [`nixpkgs-devshell`](https://www.github.com/blaggacao/nixpkgs-devshell/tree/master/shell.nix), I'd kindly request to provide an overlay.

**Comment by Mic92** [comment]
Why not just import `default.nix` with super.callPackage?

**Comment by blaggacao** [comment]
> Why not just import default.nix with super.callPackage or use it from nixpkgs?

TBH, I'm not familiar with this technique.

Would you mind showing/guiding me how that might look like [in context](https://github.com/blaggacao/nixpkgs-devshell/blob/1d37f630dee217e0bef149e873f9506592190848/shell.nix#L4-L7)?

**Comment by Mic92** [comment]
You can also just import it as a flake by the way and use the `defaultPackage`.
Otherwise:

```nix
{ pkgs ? import <nixpkgs> {} }:
let
   src = fetchFromGitHub {
     owner = "Mic92"
     repo = "nix-update";
     rev = "<to-be-filled-in>";
     sha256 = "<to-be-filled-in>";
  };
in pkgs.callPackage src {}
```

**Comment by blaggacao** [comment]
> You can also just import it as a flake by the way and use the defaultPackage.

Well, as far as I can tell, that would almost always mean a dependency on two different versiona of nixpkgs at the se.time which is really great form reproducability, but really, really, really bad for closure size.

At least, from what I can tell, my motivation to open this was to avoid the latter issue.

Your other suggestion works until `fetch*` will be eventually deprecated for usage within flakes. It's already considered an antipattern, but if it works :shrug:

**Comment by Mic92** [comment]
> > You can also just import it as a flake by the way and use the defaultPackage.
> 
> Well, as far as I can tell, that would almost always mean a dependency on two different versions of nixpkgs at the same time which is really great for reproducability, but really, really, really bad for closure size.
> 
> At least, from what I can tell, my motivation to open this was to avoid the latter issue.
> 
> Your other suggestion works until `fetch*` will be eventually deprecated for usage within flakes. It's already considered an antipattern, but if it works shrug

Not really. You can still override nixpkgs like here: https://github.com/Mic92/dotfiles/blob/e22911ae4d929bc91316a2c4a4112ad175b5bc77/flake.nix#L21
to avoid pinning nixpkgs within the flakes.

**Comment by blaggacao** [comment]
I appears to me one issue with this approach is that instantiating nixpkgs is not as cheap as we would wish it for and hence that doesn't scale very well in comparison to overlays.

Until that can eventually be regarded as solved, I guess overlays are still our best supported shot at the moon.

**Comment by Mic92** [comment]
Using the approach above is not re-instantiating nixpkgs, since it overrides nixpkgs in a flake so that every flake uses the same nixpkgs. I would even speculate that this is faster than overlays, since it does not require merging sets and easier to understand/harder to get wrong (no infinite recursion etc).

**Comment by Mic92** [comment]
But I am easily convinced if you show me actual number regarding evaluation time.

**Comment by blaggacao** [comment]
Yeah, I only have hear-say about 400MB RAM. But hearesay is circumstential evidence, "they say". :wink:

My concern would be the acumulation of invocations of `import nixpkgs { ... };` in the downstream flakes.

**Comment by Mic92** [comment]
> Yeah, I only have hear-say about 400MB RAM. But hear-say is circumstantial evidence, "they say". wink
> 
> So it might as well be false-say. Or even false-hear. shrug
> 
> Regardless, my concern would be the accumulation of actual invocations of `import nixpkgs { ... };` in the downstream flakes.

Sorry I don't understand this gibberish.

**Comment by Mic92** [comment]
flakes only import the same input once. Proof:


```
{
  description = "A very basic flake";

  inputs = {
    nixpkgs.url = path:/home/joerg/git/nixpkgs;
    flake1.url = path:./flake2;
    flake1.inputs.nixpkgs.follows = "nixpkgs";
    flake2.url = path:./flake2;
    flake2.inputs.nixpkgs.follows = "nixpkgs";
  };
  outputs = { self, nixpkgs, flake1, flake2 }: {
    packages.x86_64-linux.hello1 = flake1.packages.x86_64-linux.hello;
    packages.x86_64-linux.hello2 = flake2.packages.x86_64-linux.hello;
  };
}
```

I patched my nixpkgs to throw a trace message when importing:

```
diff --git a/default.nix b/default.nix
index faed7e26354..409f28ef5fc 100644
--- a/default.nix
+++ b/default.nix
@@ -24,5 +24,4 @@ if ! builtins ? nixVersion || builtins.compareVersions requiredVersion builtins.
   ''

 else
-
-  import ./pkgs/top-level/impure.nix
+  builtins.trace "re-imported" (import ./pkgs/top-level/impure.nix)
```

The message is only printed once:

```console
$ nix build --show-trace '.#hello2' '.#hello1'
trace: re-imported
```

**Comment by blaggacao** [comment]
Is `flake1 = ... ./flake2` a transcription error or did you use the same path as input twice?

It appears to me such would be able to invalidate the proof.

**Comment by blaggacao** [comment]
> Sorry I don't understand this gibberish.

You didn't try. :shrug:

**Comment by Mic92** [comment]
> Is `flake1 = ... ./flake2` a transcription error or did you use the same path as input twice?
> 
> It appears to me such would be able to invalidate the proof.
> 
> Make also sure to pass different `{ ... }` to the nixpkgs import, just to make sure nothing is somehow cached here.
> 
> I can't possibly conceive a way how the proof would be reproducible under that condition. It just makes no sense (to me).

Still the same even after fixing this. Also busted the evaluation cache same result.

**Comment by blaggacao** [comment]
> Still the same even after fixing this. Also busted the evaluation cache same result.

Interesting, I can't explain for myself how ...

- `import nixpkgs { config = {allowUnfree = true; }; };`
- `import nixpkgs { config = {allowUnfree = false; }; };`

... are not hit 2 times on the receiving end.

I still hesitate to belive in miracles. But you are getting me a little closer. :wink:

**Comment by Mic92** [comment]
There is no nixpkgs config if you use flakes.

**Comment by blaggacao** [comment]
> There is no nixpkgs config if you use flakes.

Oh! Oh, looks like you misunderstood me all the time: when I was talking (gibberish) about the accumulation of `import nixpkgs { ... };`l was _litterally_ talking about the accumulation of "`import nixpkgs { ... };`". (If that makes sense)

My argument is not specifically attached to the usage of flakes, but to the usage of the `import` statement within flakes.

Or are you actually _trying to make me understand_ that `import` behaves differently in the context of flakes than it does, e.g. in a repl?
