### ISSUE TITLE
Possibly incorrect expression for cargoDeps?

### ISSUE THREAD

**Issue by colinxs** [Mic92/nix-update#55]
Currently, cargoSha256 is updated as:

```
pkg.cargoDeps.overrideAttrs (_: {{ inherit sha256; }})
```

I'm curious if this is correct. Based on the source for `fetchCargoTarball`, `sha256` is never passed to `mkDerivation` (see the `removeAttrs` at the bottom. Wouldn't you want to override `outputHash`? Here's a similar conversation:

https://discourse.nixos.org/t/is-it-possible-to-override-cargosha256-in-buildrustpackage/4393

Note that they also override the `src` attribute for both `cargoDeps` and the package.

**Comment by figsoda** [comment]
looks like it's fixed in #100
