### ISSUE TITLE
Add support for flakes package output

### ISSUE THREAD

**Issue by Kranzes** [Mic92/nix-update#83]
It would be great if `nix-update` supported updating hashes of packages exposed via the `packages` output of a flake.

**Comment by Mic92** [comment]
Biggest problem here is to get the flake directory. Flakes uri will only contain nix store paths.

**Comment by Mic92** [comment]
unsafeGetAttrPos won't work well on flakes:

```
cd nixpkgs
nix-repl> :lf .#
nix-repl> builtins.unsafeGetAttrPos "src" legacyPackages.x86_64-linux.hello
{ column = 3; file = "/nix/store/24m5pbxa7j4j6ic1nmmywcjhwsraqnvn-source/pkgs/applications/misc/hello/default.nix"; line = 14; }
```

**Comment by Kiskae** [comment]
You could use `self.outPath` to figure out the store location for the current flake, then replace it with the current directory to get the file location in the repository?

**Comment by figsoda** [comment]
@Kiskae thanks for the tip, I opened #118
