### ISSUE TITLE
Add changelog to commit message

### ISSUE THREAD

**Issue by mweinelt** [Mic92/nix-update#87]
Making use of `meta.changelog` to embed the changelog URL into the commit message would be a neat way to automatically create links to them, which are useful during review.

- getting `pkg.meta.changelog or null` is easy
- running eval another time is probably required to let nix interpret `meta.changelog` post-update & pre-commit
- append to commit message with two newlines if it exists

That's all.

**Comment by mweinelt** [comment]
Proposed for nixpkgs CONTRIBUTING.md in https://github.com/NixOS/nixpkgs/pull/200922.

**Comment by Mic92** [comment]
sound nice to have.

**Comment by Mic92** [comment]
https://github.com/Mic92/nix-update/pull/101

**Comment by Mic92** [comment]
This is merged now.
