### ISSUE TITLE
Using pname prefix breaks some tagging convention with github

### ISSUE THREAD

**Issue by jonringer** [Mic92/nix-update#9]
example would the the `python3Packages.lxml` package, the original:
```
buildPythonPackage rec {
  pname = "lxml";
  version = "4.5.0";

  src = fetchFromGitHub {
    owner = pname;
    repo = pname;
    rev = "${pname}-${version}";
    sha256 = "1i3bhg8xb502afq4ar3kgvvi1hy83l4af2gznfwqvb5b221fr7ak";
  };
```
but then nix-update wants to change this to:
```
The package python3.8-lxml-lxml-4.5.1 will be fetched as follows:
> fetchFromGitHub {
>   owner = "lxml";
>   repo = "lxml";
>   rev = "lxml-lxml-4.5.1";
>   sha256 = "1i3bhg8xb502afq4ar3kgvvi1hy83l4af2gznfwqvb5b221fr7ak";
> }

trying https://github.com/lxml/lxml/archive/lxml-lxml-4.5.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   126  100   126    0     0    229      0 --:--:-- --:--:-- --:--:--   229
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

maybe have a way to try with the prefix, then try without a prefix? or have an option to not touch rev?

**Comment by Mic92** [comment]
It might be possible to set `version = "";` and than see what the computed prefix is and substract that from the new prefix.

**Comment by Mic92** [comment]
This can be now worked around with https://github.com/Mic92/nix-update/releases/tag/0.3

**Comment by doronbehar** [comment]
@Mic92 would it be possible for you to give an example of how to use the `--version-regex` option for the package mentioned here, or for `tectonic`'s version scheme that is mentioned in https://github.com/Mic92/nix-update/issues/19 ?

**Comment by SuperSandro2000** [comment]
``nix-update --build --commit --version-regex 'mdcat-(.*)' -- mdcat``
``nix-update --build --commit --version-regex 'gopls\%2Fv(.*)' -- gopls``
